- app/assets/data/APIConnection.js
- app/assets/data/Fetcher.js
- app/containers/Home.js
- app/containers/LogIn.js
- app/containers/Matches.js
- app/containers/Profile.js
- app/containers/SignUp.js
Added some documentation and refactored some code
> Documentation & Refactoring

- backend/index.js
- backend/utils/DatabaseManager.js
Merged Users collection and ProfileCards collection
> Updated database and Back-end to work with new database design

- app/assets/data/APIConnection.js
- app/containers/Home.js
- app/containers/Profile.js
- backend/index.js
Also fixed a bug causing missing image urls for users on the back-end
> Updated front end logic to work with new back-end

- backend/index.js
Setup GitHub webhook to send post request to the back-end on updates to master. On receiving the update, the active instance starts replying with status code 503 to health checks causing the Load balancer to tag that instance as "unhealthy". This triggers a new deployment which pulls the latest code thus completing the update. The outdated instance is destroyed after the new instance is deployed
> GitHub Webhook Setup

- backend/index.js
Last PR accidentally removed the signed GET Url that was need for the client to download user images.
Note: Please test any and all code that is changed in a PR. Don't approve them without testing otherwise a bug more serious than this can get through and cause a lot of issues. That's the whole point of a PR. Testing and Reviewing the code written by someone else.
> Fixed Missing GET Url in the last PR

- app/components/CardItem.js
- app/containers/Home.js
- app/containers/Matches.js
- backend/index.js
- backend/utils/AWSPresigner.js
- backend/utils/Chat.js
- backend/utils/DatabaseManager.js
- backend/utils/Matcher.js
- dev-server-config/.gitignore
PR #13 caused keywords to disappear. This patch fixes it
> Missing keywords fix

- backend/index.js
Added updateProfilePicture to allow user to add a profile picture.
Send a GET request with email in the query and the server will respond with a signedPutURL that can be used to send a PUT request with the updated profile picture.
> added updateProfilePicture

- .github/workflows/backend.yml
- backend/package.json
> Setup CI for backend

- backend/index.js
> Fixed updateProfilePicture route

- backend/index.js
- backend/utils/DatabaseManager.js
- backend/utils/Handlers.js
Updated verification hash generation to removed periods at the end of the hash. Updated delete user in handlers.js to delete user from the database. 
Fixes #78 
Fixes #85
> Updated verification hash generation. Updated deleteUser in Handlers.js

- backend/notes
- backend/test/test.js
- backend/utils/Matcher.js
> fixed the delete user bug

- backend/index.js
- backend/test/test.js
> Fixed email verification bug

- backend/test/test.js
- backend/utils/Chat.js
- backend/utils/Matcher.js
> fixed blocked user bug

- backend/index.js
- backend/utils/DatabaseManager.js
Implemented chunk loading for messages.
Fixes #58 
Co-authored by @Lakshya2610
> Implemented messages chunk loading

- app/android/gradle.properties
- app/assets/data/APIConnection.js
- app/containers/Matches.js
- app/containers/Settings.js
- app/package-lock.json
> logout feature implemented

- backend/.gitignore
- backend/LoadTesting.yml
- backend/index.js
- backend/package-lock.json
- backend/package.json
- backend/test/test.js
- backend/users.csv
> added load testing script

- dev-server-config/main.tf
Updated server config on AWS to support a test server on port 8100
> Server config update for testing

- app/assets/styles/index.js
- app/components/CardItem.js
- app/containers/Chat.js
- app/containers/Matches.js
Increased size of home cards
Aligned additional info cards properly
Made chat UI changes
Removed padding on Matches page that initially caused cards to get cut off.
> UI changes to Home, Chat and Matches

- app/assets/data/APIConnection.js
- app/assets/styles/index.js
- app/components/CardItem.js
- app/components/MatchPopup.js
- app/components/ProfilePopup.js
- app/containers/Home.js
- app/containers/Matches.js
- app/containers/SignUp.js
- app/containers/Verifiy.js
- package-lock.json
- Fixed the masks for popups
- final checks needed to see match popup work properly
- Fixed a small bug where app wouldn't process signup if the email given was already in use
> Masks and other issues

- backend/index.js
Updated code to store date of birth instead of age
> added gender option for other and prefer not to say

- app/android/gradle.properties
- app/assets/data/APIConnection.js
- app/components/CachedImage.js
- app/components/CardItem.js
- app/components/OtherProfileItem.js
- app/components/ProfileItem.js
- app/containers/Home.js
- app/containers/Matches.js
- app/containers/Messages.js
- app/containers/Onboarding.js
- app/containers/OtherProfile.js
- app/containers/OtherProfile2.js
- app/containers/Profile.js
Fixed the bug that caused updated profile pictures to not be re-downloaded due to cached images
Fixes #124
> Fixed Image caching bug caused by update profile picture

- backend/index.js
Added support to store checksum for profile picture of each user
Fixes #123
> Added support for checksums for profile picture

- app/android/gradle.properties
- app/assets/styles/index.js
- app/components/CachedImage.js
- app/components/MatchPopup.js
- app/components/ProfileItem.js
- app/containers/Chat.js
- app/containers/Home.js
- app/containers/Matches.js
- app/containers/Profile.js
- app/package-lock.json
1. Fixed UI on Match popup, (Still need to pass image, name and email of the matched user properly)
2. Fixed Messages page to show last message of the conversation
3. Test cached image with checksums, works as expected
4. Updated profile picture to be touchable. Deleted pen icon to update profile picture
> Beta UI fixes

- backend/package.json
Version 1.0.0 for the backend is now complete
> updated build no to 1.0.0 (beta build)

- app/containers/SplashScreen.js
reduced the time to 800 ms which should be what we need #143
> Fixed SplashScreen

- app/assets/styles/index.js
- app/components/ProfileItem.js
- app/components/TagClubs.js
- app/components/TagCourses.js
- app/containers/SignUp.js
Profile page doesn't bug out because of empty courses or keywords anymore.
Fixes #148
> Profile page bug fixed

- app/assets/styles/index.js
- app/containers/SignUp.js
> Updated textbox colors on signup page

- app/android/gradle.properties
- app/components/CachedImage.js
- app/components/ProfileItem.js
- app/containers/Home.js
- app/containers/Profile.js
- app/containers/SignUp.js
- app/package-lock.json
Added border around profile photo.
> Placeholder bug temporarily fixed

- backend/index.js
- dev-server-config/main.tf
- dev-server-config/variables.tf
1. Added SSL certificate for API.
2. Added automatic HTTP to HTTPS redirection
> HTTPS Support for the API

- backend/index.js
- dev-server-config/main.tf
Last update to the server caused it to go in an infinite reboot cycle (😅). This fixes the bug
> Added separate route for health check for the Load Balancer

- .github/workflows/backend.yml
- backend/index.js
- backend/package-lock.json
- backend/package.json
- backend/utils/Chat.js
Added socket.io-redis to allow for horizontal scaling with sockets for chat
Fixes #51
> Socket.io-redis integration
